name: Sync Upstream

on:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/fiterpaystack/web-app.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Create sync branch
        run: |
          git checkout -B sync-upstream upstream/main
          git push origin sync-upstream --force

      - name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync from fiterpaystack/web-app upstream repo'
          branch: sync-upstream
          title: '🔄 Sync from fiterpaystack/web-app'
          body: 'Sync from upstream repo(fiterpaystack/web-app)'
