name: Sync Upstream

on:
  workflow_dispatch:

env:
  UPSTREAM_BRANCH: main
  UPSTREAM_URL: https://github.com/fiterpaystack/web-app.git
  UPSTREAM_REPO: fiterpaystack/web-app

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          echo "Adding upstream remote: ${{ env.UPSTREAM_URL }}""
          git remote add upstream ${{ env.UPSTREAM_URL }}

      - name: Fetch upstream
        run: |
          echo "Fetching changes from upstream repository"
          git fetch upstream

      - name: Create sync branch
        run: |
          echo "Creating sync-upstream branch from upstream/${{ env.UPSTREAM_BRANCH }}"
          git checkout -B sync-upstream upstream/${{ env.UPSTREAM_BRANCH }}

      - name: Restore .github/workflows from main
        run: |
          echo "Restoring .github/workflows directory from origin/main to discard upstream changes"
          git restore -s origin/main .github/workflows

      - name: Commit restored workflow files
        run: |
          echo "Committing restored .github/workflows to discard upstream workflow changes"
          git commit -am "Discard upstream github/workflow files"
        continue-on-error: true

      - name: Pushing sync-upstream branch
        run: |
          echo "Pushing changes to sync-upstream branch"
          git push origin sync-upstream --force

      - name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Sync from ${{ env.UPSTREAM_REPO }} upstream repo'
          branch: sync-upstream
          title: '🔄 Sync from ${{ env.UPSTREAM_REPO }}'
          body: 'Sync from upstream repo(${{ env.UPSTREAM_REPO }})'
