name: Trigger Paystack-MFB web-app Workflow

on:
  push:
    branches:
      - main
jobs:
  trigger-workflow:
    name: Trigger Workflow in Paystack-MFB/web-app to fetch upstream changes
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          owner: Paystack-MFB
          permission-actions: write

      - name: Trigger workflow in Paystack-MFB/web-app
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: Paystack-MFB/web-app
          workflow: fetch-upstream-origin-changes.yml
          ref: main
